### ISSUE TITLE
Failed to load the atom-antescofo package

### ISSUE THREAD

**Issue by jsbean** [nadirB/atom-antescofo#1]
**Steps to reproduce:**

1. Install `atom-antescofo` via `Atom Package Installer`

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [atom-antescofo](https://github.com/nadirB/atom-antescofo) package, v1.0.3-beta

### Stack Trace

Failed to load the atom-antescofo package

```
At variable @green is undefined in /Users/BEAN/.atom/packages/atom-antescofo/styles/antescofo.less:119:10

LessError: variable @green is undefined
  at /Users/BEAN/.atom/packages/atom-antescofo/styles/antescofo.less:119:10
```

**Steps to fix:**

Either:
- Require dependency: `atom-antescofo-syntax`
- Revert `@import "colors";` to
`@import "../../atom-antescofo-syntax/styles/colors.less";`

Or:
- Include `colors.less` in `styles/`

**Comment by nadirB** [comment]
thanks for the report. I'll check that asap.

**Comment by jsbean** [comment]
👍

**Comment by nadirB** [comment]
for the moment colors.less is included in styles/ (any better ?)
There is a deprecation since Atom las version... have to prepend all syntax selectors with **syntax--** 
to be continued...

**Comment by programLyrique** [comment]
It should be now solved!
