### ISSUE TITLE
Add Antescofo commands via OSC

### ISSUE THREAD

**Issue by programLyrique** [nadirB/atom-antescofo#2]
This nodejs lib https://github.com/colinbdclark/osc.js/ seems to handle OSC well, and there are even instructions on how to use it with Electron (the custom nodejs backend of atom).

See also http://flight-manual.atom.io/hacking-atom/sections/package-modifying-text/ at section _See the ASCII art_ to see how to integrate a nodejs package in Atom.

**Comment by nadirB** [comment]
This SuperCollider development environment for Atom.io uses OSC 
[https://github.com/crucialfelix/atom-supercollider]

**Comment by nadirB** [comment]
[](https://github.com/crucialfelix/atom-supercollider)

**Comment by programLyrique** [comment]
Yes, they don't use directly OSC but they have a dependency to the node library supercolliderjs https://github.com/crucialfelix/supercolliderjs which uses an osc lib called osc-min https://github.com/russellmcc/node-osc-min

**Comment by nadirB** [comment]
finally implemented thanks to Benjamin Levy 👍
